export const themes = {
    light: {
      primaryColor: "#f8f9fa",
      playButtonColor: "#17a2b8",
      secondaryColor: "#e9ecef",
      accentColor: "#ffc107",
      warningColor: "#000000",
      SidenavBackgroundColor:"#1C1C1E",
      textColor: "#1C1C1E",
      secondaryTextColor:"#f8f9fa",
      backgroundGradient: "linear-gradient(to right, #f8f9fa, #edeff2)",
    },
    dark: {
      primaryColor: "#1C1C1E",
      playButtonColor: "#17a2b8",
      secondaryColor: "#6c757d",
      accentColor: "#17a2b8",
      warningColor: "#ffc107",
      SidenavBackgroundColor:"#1C1C1E",
      textColor: "#f8f9fa",
      secondaryTextColor:"#f8f9fa",
      backgroundGradient: "linear-gradient(to right, #0c0c17, #1a1a2e)",
    },
    city_lights: {
      primaryColor: "#1C1C1E",
      playButtonColor: "#7F39FB",
      secondaryColor: "#2C2C2E",
      accentColor: "#7F39FB",
      warningColor: "#000000",
      SidenavBackgroundColor:"#1C1C1E",
      textColor: "#FFFFFF",
      secondaryTextColor:"#f8f9fa",
      backgroundGradient: "linear-gradient(to right, #1a1a2e, #2c3e50)",
    },
    spotify_green: {
      primaryColor: "#1DB954",
      playButtonColor: "#1C1C1E",
      secondaryColor: "#282828",
      accentColor: "#1C1C1E",
      warningColor: "#1C1C1E",
      SidenavBackgroundColor:"#1C1C1E",
      textColor: "#FFFFFF",
      secondaryTextColor:"#f8f9fa",
      backgroundGradient: "linear-gradient(to bottom, #222222, #1DB954)",
    },
  };
  